
title: "Grimán DevWorks"
email:
email_user: "griman"
email_domain: "gmail.com"
description: "Griman DevWorks | Projects | About"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajgriman.github.io"
# url:
# twitter_username: jekyllrb
github_username:  ajgriman

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-seo-tag

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets/", "scripts/"] # Add "admin/" if you have it

polyglot:
  default_lang_in_url: false 
  parallel_localization: false 
  # relative_permalinks: false
  pages_mode: filename
collections:
  projects:
    output: true
    permalink: /projects/:title/ 
  tech_icons: 
    output: false 
defaults:
  - scope:
      path: "about.md"
    values:
      layout: "about"
  - scope:
      path: "about_es.md"
    values:
      layout: "about"
